import styled from 'styled-components';

export const HourlyDiv = styled.div`
	padding-top: 3.5rem;
	background: rgba(255, 255, 255, 0.5);

	* {
		margin: 0;
		box-sizing: border-box;
	}

	.hide-extra-hours {
		box-sizing: border-box;

		height: 119px;

		display: grid;
		grid-template-columns: repeat(12, auto);
		grid-template-rows: repeat(3, 118px);
		color: black;
		text-align: center;
		grid-auto-rows: 0; /* set height to 0 for autogenerated grid rows */

		overflow: hidden; /*hide grid items that overflow */

		transition: 1s;
	}

	.show-all-hours {
		display: grid;

		height: 356px;

		grid-template-columns: repeat(12, auto);
		grid-template-rows: repeat(3, 118px);
		color: black;
		text-align: center;
		grid-auto-rows: 0; /* set height to 0 for autogenerated grid rows */

		overflow: hidden; /* hide grid items that overflow */

		transition: 1s;
	}

	.hour {
		border: 1px solid grey;
		background: rgba(30, 124, 255, 0.5);
		padding: 9px;
	}

	.hour-top {
		font-weight: bold;
	}

	.icon img {
		height: 3rem;
	}

	.degree {
	}
`;

export const MoreArrow = styled.div`
	background: rgba(255, 255, 255, 0.5);

	* {
		margin: 0;
		padding: 0;
		box-sizing: border-box;
	}

	p {
		padding: 3px 3px 0px 3px;
		display: inline;
		vertical-align: bottom;
	}

	.chevron {
		position: relative;
		top: -1.3rem;
		left: 0.3rem;
		width: auto;
		padding-bottom: 7rem;
	}

	.chevron img {
		height: 1rem;
		padding: 0;
	}

	.chevron img:hover {
		cursor: pointer;
		opacity: 0.4;
	}

	.show-all-btn {
		transition: 300ms;
		transform: rotate(180deg);
	}

	.hide-extra-btn {
		transform: rotate(0);
		transition: 300ms;
	}
`;
